swift_version = "3.1"
platform :ios, '10.0'
use_frameworks!

target 'ScrollableStackView_Example' do
  pod 'ScrollableStackView', :path => '../'

  target 'ScrollableStackView_Tests' do
    inherit! :search_paths

    
  end
end
